name: Auto Scrape & Store News

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium scrapy pypyodbc pandas beautifulsoup4 langdetect langid

      - name: Setup Firefox & Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox wget unzip
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz
          tar -xvzf geckodriver-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver
          
          # Verify installation
          firefox --version
          geckodriver --version

          chromedriver --version


      - name: Run News Scraper
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python news_scrape.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update news data"
          git push || echo "No changes to commit"
